from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class CommandRequest:
    """
    Logical command generated by the Core Engine.

    It contains no transport-specific information (MQTT topic,
    QoS, payload encoding, etc.). Those details are resolved
    later by the CommandRouter using the Registry.
    """

    entity_id: str

    action: str

    parameters: dict[str, Any] = field(default_factory=dict)

    source: str = "core"
